name: Waka Readme Stats

on:
  push:
    branches: [master]
    pull_request:
      branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "False"
          IGNORED_REPOS: "zelhajou,1337-playground,OctoMolar-frontend,OctoMolar-backend,OctoMolar-main,world-map-puzzle"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
